#! /bin/bash
#
# @file link.sh
#
# Copyright © 2014 Jim Zhan <jim.zhan@me.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

here="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"


log() {
    printf '\033[0;34m%s\033[0m\n' "${1}"
}

info() {
    printf "\e[34m[I]\e[0m ${1}\n"
}

error() {
    printf "\e[31m[✘]\e[0m ${1}\n"
}

success() {
    printf "\e[32m[✔]\e[0m ${1}\n"
}



link() {
    if [ -L ${2} ]; then
        unlink ${2}
    elif [ -e ${2}  ]; then
        info "Existing ${2} found, Moving ${2} -> ${2}.previous"
        mv ${2} ${2}.previous
    fi
    ln -s ${1} ${2}
    success "${2} -> ${1}"
}

link ${here}/vim 			$HOME/.vim
link ${here}/vimrc 			$HOME/.vimrc

success "VIM's settings has been updated, starting Vim..."
vim
